apiVersion: v1
kind: Service
metadata:
  name: aks-workflow-demo
  namespace: namespace-workflow-1741096652076
  labels:
    app.kubernetes.io/name: aks-workflow-demo
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: aks-workflow-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080